OUTPUT_DIR: 'output_0614/palmlab_190'
GPUS: '''0,1,2'''
NUM_WORKERS: 8
PRINT_FREQ: 100
DEBUG_FREQ: 200
MODEL:
  PRETRAINED: '' #'pretrained_models/hrnetv2_w48_imagenet_pretrained.pth'
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
DATASET:
  ROOT: '/disk1/panzhiyu/THUPALMLAB/'
  NUM_CLASSES: 16 # It is the same with out channels
TRAIN:
  BATCH_SIZE_PER_GPU: 8
  LR: 0.0001
  EPOCHS: 1000
  SHUFFLE: True
  PATCH_SIZE: 192
TEST:
  BATCH_SIZE_PER_GPU: 1

